
name: Build and deploy to Cloud Run

on:
  workflow_call:
    inputs:
      environment:
        description: 'The environment to deploy to'
        required: true
        type: string
      cloud_run_service:
        description: 'The name of the Cloud Run service to deploy to'
        required: true
        type: string
      gar_repo_name:
        description: 'The name of the Google Artifact Registry repo to push the container to'
        required: true
        type: string
      gcp_project_id:
        description: 'The ID of the GCP project to deploy to'
        required: true
        type: string
      gcp_region:
        description: 'The region of the GCP project to deploy to'
        required: true
        type: string

jobs:
  build_and_deploy:
    name: Build and deploy
    runs-on: ubuntu-latest

    environment: ${{inputs.environment}}

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Set up GAR base URL
      run: echo "ARTIFACT_BASE_URL=${{inputs.gcp_region}}-docker.pkg.dev" >> $GITHUB_ENV

    - name: Set the GAR repo URL
      run: echo "ARTIFACT_REPO=${{env.ARTIFACT_BASE_URL}}/${{inputs.gcp_project_id}}/${{inputs.gar_repo_name}}/${{inputs.cloud_run_service}}:${{ github.sha }}" >> $GITHUB_ENV

    - name: Checkout
      uses: actions/checkout@v3.2.0

    - id: 'auth'
      uses: 'google-github-actions/auth@v1.0.0'
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}
        token_format: 'access_token'

    - name: Docker Auth
      id: docker-auth
      uses: 'docker/login-action@v2.2.0'
      with:
        username: 'oauth2accesstoken'
        password: '${{ steps.auth.outputs.access_token }}'
        registry: '${{ inputs.gcp_region }}-docker.pkg.dev'

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1.0.1

    - name: Authorize docker push
      run: gcloud auth configure-docker ${{ inputs.gcp_region }}-docker.pkg.dev --quiet

    - name: Build container
      run: |
        docker build \
          -t ${{ env.ARTIFACT_REPO }} \
          -f Dockerfile .

    - name: Push container
      run: docker push ${{ env.ARTIFACT_REPO }}

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy ${{ inputs.cloud_run_service }} \
          --region ${{ inputs.gcp_region }} \
          --image ${{ env.ARTIFACT_REPO }} \
          --platform "managed" \
          --quiet
