name: Deploy to production

on:
  workflow_run:
    branches:
      - main
    workflows:
      - Tests
    types:
      - completed

jobs:
  build_and_deploy:
    uses: ./.github/workflows/build-deploy.yml
    with:
      environment: prod
      cloud_run_service: nettopp-auth-api
      gar_repo_name: nettopp-auth
      gcp_project_id: nettopp
      gcp_region: europe-west1
    secrets: inherit
